dist: xenial
sudo: required
language: python
install:
  - pip install -r requirements.txt

env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "GEbQy4zR5hhHDzjoThGyCHZVmpEWKduwR/sZ1sR8csOYrfYqQTHinhAMY+KAdUhjJfWGwR9l2v2xkhyokzdADhKOqZJo7jkkioPEtENdocTWMYq7Qedg6kUCzcAutURIBCcoJtW4vrpGZ+1YR4vB8BhA11KA62QUbsQY3ds/LTg="
    - secure: "NbHt1OUyrTXmN+tYAFcGH3mxlxraDKJ6WQNTJTG+u+wTOzh2MU1bf59l+oanvqlydpd7ZzG7c2cUpje5hvBMEV9s9jwdWqTlGXHWpcU3a1wZdNOkkAPK0Cb3opabRLwIqjovaoAAouSJCq/jUADzhusjrZcn5JVA7sSpYyJT3uE="

# command to run tests
# TODO: Save a dockerhub image and use that instead of building it each time?
script:
  - make build-docker-image
  - cd test/dockerfiles/condor && ./chmod +ax ./start_condor_docker.sh && ./start_condor_docker.sh && cd ../../
  - pytest test/condor/execution_engine2_scheduler_test.py

after_success:
  - IMAGE_NAME=kbase/ee2 ./build/push2dockerhub.sh
